### ISSUE TITLE
Copy Constructor for Contents needed

### ISSUE THREAD

**Issue by jyutzler** [ngageoint/geopackage-core-java#31]
The use case is copying data from multiple GeoPackages (each of which have a single bit of contents) to a single GeoPackage. However, my input GeoPackages all have the same user data table name. What I want to be able to do is acquire a Contents object (`inputContents = inputContentsDao.getContents(ContentsDataType.TILES).get(0)`), copy it (`outputContents`), and change its name so that I can use it on the output GeoPackage (`outputContentsDao.create(outputContents)`).

I can do this manually but it would be much better with a reliable/verified copy constructor in place.

**Comment by bosborn** [comment]
Currently you can read a Contents, change the name and identifier (since it is required to be unique), and save the contents if you have created the corresponding feature or tile table.

Example:
```
Contents copyContents = dao.queryForAll().get(0);
copyContents.setTableName("new_table");
copyContents.setIdentifier(copyContents.getTableName());
		
geoPackage.createFeatureTable(TestUtils.buildFeatureTable(
   copyContents.getTableName(), "geom", GeometryType.GEOMETRY));
		
dao.create(copyContents);
```

Does this solve what you are trying to do?

**Comment by jyutzler** [comment]
No because I still need the original contents object in its original form to read from the original tables. Calling dao.queryForAll().get(0) multiple times returns the same object each time and since there is only one, you can't change it without breaking other things that use it.

I think all we need is something akin to: 
```
	/**
	 * Copy Constructor
	 */
	public Contents(Contents input){
		setId(input.getId());
		setDataType(input.getDataType());
		setDescription(input.getDescription());
		setIdentifier(input.getIdentifier());
		setSrs(input.getSrs());
		setLastChange(input.getLastChange());
		setBoundingBox(input.getBoundingBox());
	}
```

**Comment by bosborn** [comment]
Added a copy constructor to Contents and Spatial Reference System on the develop branch (3fa2c50) with [tests in geopackage-java](http://github.com/ngageoint/geopackage-java/commit/17551b0239c911ec2e46ee34bbf0919878204fe1).  Let me know if that works for you.  Will add the rest of the copy constructors, matching [geopackage-ios](https://github.com/ngageoint/geopackage-ios) changes, and tests later.

**Comment by bosborn** [comment]
Added copy constructors to the rest of the base table, extension, and user table (tile, feature, attributes) objects.  Currently on the develop branch.  Will go out on the geopackage-core-java 1.2.3, geopackage-java 1.2.3, and geopackage-android 1.3.3 releases.

**Comment by jyutzler** [comment]
I think to test this properly, you need to make a change to one of the two objects and verify that it is not reflected in the other. I didn't see any evidence of this, though maybe I missed it.

**Comment by bosborn** [comment]
I added a few more checks in the Contents test for you.  We don't really need to worry about immutable variable types in the objects though.

I did however make some changes to the user tables (tile, feature, attributes) so that blobs / byte arrays and geometries are cloned as different object references.  I still need to take a look at better support for dates in the user tables.

**Comment by bosborn** [comment]
Added and released in:
geopackage-core-java [1.3.0](https://github.com/ngageoint/geopackage-core-java/releases/tag/1.3.0)
geopackage-java [1.3.0](https://github.com/ngageoint/geopackage-java/releases/tag/1.3.0)
geopackage-android [1.4.0](https://github.com/ngageoint/geopackage-android/releases/tag/1.4.0)
geopackage-android-map [1.4.0](https://github.com/ngageoint/geopackage-android-map/releases/tag/1.4.0)
