### ISSUE TITLE
Related tables are created and validated using a wrong data type

### ISSUE THREAD

**Issue by fjlopez** [ngageoint/geopackage-core-java#41]
The method `createRelatedTable` in `RelatedTablesCoreExtension` creates a new related table when needed using as data type the name of the relation (i.e. `features`,  `media` or `simple_attributes`):
https://github.com/ngageoint/geopackage-core-java/blob/24ba2ebe4f4ba3a7e2655875bc306f1f62e97b7e/src/main/java/mil/nga/geopackage/extension/related/RelatedTablesCoreExtension.java#L662
And validates existing related tables data type agains using the name of the relation:
https://github.com/ngageoint/geopackage-core-java/blob/24ba2ebe4f4ba3a7e2655875bc306f1f62e97b7e/src/main/java/mil/nga/geopackage/extension/related/RelatedTablesCoreExtension.java#L576-L587
Contents of new related tables also perform a similar check:
https://github.com/ngageoint/geopackage-core-java/blob/24ba2ebe4f4ba3a7e2655875bc306f1f62e97b7e/src/main/java/mil/nga/geopackage/extension/related/UserRelatedTable.java#L103-L104

However, the current draft of the [GeoPackage Related Tables Extension ](http://www.geopackage.org/18-000.html) states that the GKPG type of the related table shall be `attributes` for [`media`](http://www.geopackage.org/18-000.html#_media) and [`simple_attributes`](http://www.geopackage.org/18-000.html#_simple_attributes) relationships.   

The current behaviour hinders the usage of GPKG files created with this implementation. For example, GDAL 2 is able to list `simple_attributes` tables when no `attributes` tables are present. When any  `attributes` table is present, it ignores `simple_attibutes` and `media` tables by default. This behaviour affects QGIS 3 as it uses the default configuration of the underlying GDAL library and then hides `simple_attributes` tables when they are mixed with `attributes` tables. 

Possible solutions:
- Extend `RelationType` to store in a field (e.g. `contentDataTypeName`) the data content type associated with the relation and use it instead of the relation name for creating and validating content.
- Make `UserRelatedTable` subclass of `AttributesTables` and perform required validations in `setContents`.

**Comment by bosborn** [comment]
Fixed [here](https://github.com/ngageoint/geopackage-core-java/commit/8414e4222fd24bc843fa0681ee6d487aa4aac309) with test updates [here](https://github.com/ngageoint/geopackage-java/commit/090d60244971e7502363e4182fc4d00e49e23581).
Updated example GeoPackage [here](https://github.com/ngageoint/GeoPackage/blob/master/docs/examples/java/example.gpkg).

I agree with opengeospatial/geopackage#459 to make that more clear.

**Comment by bosborn** [comment]
Fixed in [3.1.0](https://github.com/ngageoint/geopackage-core-java/releases/tag/3.1.0)
