### ISSUE TITLE
getCentroid().getZ() returns null

### ISSUE THREAD

**Issue by brianchenpg** [ngageoint/geopackage-core-java#42]
Please fill out as much known and relevant information as possible.

#### Version Information:

  * GeoPackage Core Java Version: 3.1.0
  * GeoPackage Core Java Source: (e.g. Central Repository, Release, Source Code Build)
  * IDE Name & Version: Eclipse Version: Neon.1a Release (4.6.1)
  * Maven Version: (mvn -version)
  * Java Version: (java -version):1.8
  * Platform & OS: Ubuntu 16.04 LTS
  * Other Relevant Libraries:

#### Expected Results:
geometry.getCentroid().getZ();
  * What did you expect to happen?
Return Double
#### Observed Results:
Return null
always
  * What happened instead?
  * How often does this occur?

#### Output:

  * Any logs, errors, or output messages?

#### Steps to Reproduce:

  1. Step One
  2. Step Two
  3. ...

#### Relevant Code:

```java
// Code to reproduce the problem?
```
		ResultSet resultSet = SQLUtils.query(connection, sql, null);
		int resultSetCount = SQLUtils.count(connection, sql, null);
		FeatureResultSet featureResultSet = new FeatureResultSet(featureDao.getTable(), resultSet,
				resultSetCount);
	
		try{
			FeatureRow featureRow = featureResultSet.getRow();
			
			GeoPackageGeometryData geometryData = featureRow.getGeometry();
			Geometry geometry = geometryData.getGeometry();
			geometry.getGeometryType();
			if (geometry.hasZ()) {
				//double z = geometry.getCentroid().getZ().doubleValue();
				//Double corZ = new Double(geometry.getCentroid().getZ()); //getZ() failed cause location null error
				geometry.getCentroid().getZ();
				System.out.println("Output Z");
				System.out.println(geometry.getCentroid().getZ()); // null error
				}
		}catch (Exception e) { 
     			e.printStackTrace();
     			//Component parent;
				//JOptionPane.showMessageDialog(parent,"Open Geopackage Database failed!","",JOptionPane.ERROR_MESSAGE);
     		} 
#### Test Files:

  * Links to any files needed for testing?

#### Additional Information:

  * Looks like the file below only has x/y for a point, missing Z and M.
https://github.com/ngageoint/simple-features-java/blob/master/src/main/java/mil/nga/sf/util/centroid/CentroidPoint.java

**Comment by bosborn** [comment]
Those centroid calculations are for 2 dimensional representations of the geometries, using only the x and y values.  So a null z and m on a calculated centroid point is always expected.  A different centroid calculation would be required to find the 3 dimensional centroid (mean position of all points in all coordinate directions).

**Comment by brianchenpg** [comment]
This is a bug. There is an existing getZ() method returns nothing but a null and nowhere mentioned on any document.

**Comment by bosborn** [comment]
This is not a bug, rather a desired feature or enhancement.  You may implement 3d centroids (or other desired utilities) and submit a pull request to [simple-features-java](https://github.com/ngageoint/simple-features-java).

I [updated the Javadoc](https://github.com/ngageoint/simple-features-java/blob/7f308796e56e8c12c607f2a86ebc1214e9221b93/src/main/java/mil/nga/sf/Geometry.java#L117) for the next simple-features-java release to reflect the 2 dimensional calculation.

All or some of the points within your geometry should contain a z value.  If you are looking for a single z value, you may decide which value to use (average, nearest neighbor, etc) based upon your needs.  The geometry hasZ() method determines if the points within the Geometry have z points, which has nothing to do with the current 2d getCentroid() calculation.
