### ISSUE TITLE
Slow Performance

### ISSUE THREAD

**Issue by snodnipper** [ngageoint/geopackage-core-java#43]
I have been testing geopackage-java by writing 10-50 million trivial geometries.  I get relatively poor performance when compared to, say, fastcsv.  On a reasonable machine I get ~25 million geometries written an hour.

During my fairly modest investigation, I could not get `Connection connection = DriverManager.getConnection("jdbc:sqlite::memory:");` working, including:

```java
SQLiteConfig config = new SQLiteConfig();
// config.setReadOnly(true);   
config.setSharedCache(true);
config.recursiveTriggers(true);
// ... other configuration can be set via SQLiteConfig object
Connection conn = DriverManager.getConnection("jdbc:sqlite::memory:", config.toProperties());
or
Connection conn = DriverManager.getConnection("jdbc:sqlite:file:memdb1?mode=memory&cache=shared");
```

I also experimented with `setAutoCommit(false)` but it would appear this would need further work to support.  

Any thoughts or suggestions would be great.  Thanks!

#### Version Information:

  * GeoPackage Java Version: mil.nga.geopackage:geopackage:3.1.0
  * GeoPackage Core Java Version: mil.nga.geopackage:geopackage-core:3.1.0
  * Java Version: openjdk 11.0.2 2019-01-15
  * Platform & OS: macOS

**Comment by bosborn** [comment]
I'll have to take a look when I get some time.  Do you have an example or test you were running that you can share?

**Comment by snodnipper** [comment]
Thanks @bosborn.  Currently working 18 hr days _but_ I'll try and get something over within the week.  I'll probably generate some data as a starting point.

**Comment by bosborn** [comment]
[Added this](https://github.com/ngageoint/geopackage-java/blob/master/src/test/java/mil/nga/geopackage/test/GeoPackagePerformance.java) to test the performance.  It is currently only creating a 2 column feature table and pre-creating a single small polygon used for each insert.

Running on a MacBook Pro 2.9 GHz Intel Core i7 with auto commit disabled:
```
Features: 50,000,000
Auto Commit: false
Commit Chunk: 1,000
Total Time: 8M8.623S
Feature Average: 0.00977246 ms
```

Running with auto commit enabled, the feature average went up to about 0.70247334 ms.  There also was not a lot of gains past 1000 feature chunks.

Hot spots when running with auto commit disabled:
![Screen Shot 2019-04-09 at 6 29 26 AM](https://user-images.githubusercontent.com/11667761/55801353-1c1f0c80-5a93-11e9-97d3-3e52d84546c0.png)

Hot spots when running with auto commit enabled:
![Screen Shot 2019-04-09 at 6 32 23 AM](https://user-images.githubusercontent.com/11667761/55801366-23deb100-5a93-11e9-8867-3a43183e7ad5.png)

Try your scenario with manual commits:
```
FeatureDao dao = geoPackage.getFeatureDao(TABLE_NAME);
Connection connection = dao.getConnection();
connection.setAutoCommit(false);
...
   // After some number of inserts
   connection.commit();
```

**Comment by bosborn** [comment]
Added transaction shortcut methods in the [GeoPackage](https://github.com/ngageoint/geopackage-core-java/blob/3fd47a4746e21a65170b89637c09216adf7fa5aa/src/main/java/mil/nga/geopackage/GeoPackageCore.java#L808) and [user daos](https://github.com/ngageoint/geopackage-core-java/blob/3fd47a4746e21a65170b89637c09216adf7fa5aa/src/main/java/mil/nga/geopackage/user/UserCoreDao.java#L540).  Updated the [performance test](https://github.com/ngageoint/geopackage-java/blob/3.3.0/src/test/java/mil/nga/geopackage/test/GeoPackagePerformance.java).
