### ISSUE TITLE
Importing large gpkg files is very slow

### ISSUE THREAD

**Issue by acespring78** [ngageoint/geopackage-core-java#44]
I have an Android application and I would like to load a very large GeoPackage file that is around 2.0 GB large. I'm using the `geopackage-android-map` package as my dependency, which internally depends on `geopackage-android`, which in turn depends on `geopackage-core-java`. All libraries are running on `3.2.0` version.

When I call `GeoPackageManager#importGeoPackage`, that 2GB file loads about ~1 minute. I traced it down ultimately inside `GeoPackageIOUtils#copyStream`, and it appears that we are copying to the buffer at 1K chunks. For reasonably small files this is ok, but if the map spans in the GB, a 1K buffer is too small.

Would it be possible to make this buffer size configurable depending on the size of the file? Or perhaps default the buffer size to 4K (or maybe even 8K) chunks?

#### Version Information:

  * GeoPackage Core Java Version: `3.2.0`
  * GeoPackage Core Java Source: (e.g. Central Repository, Release, Source Code Build)
  * IDE Name & Version:
  * Maven Version: (mvn -version) `Apache Maven 3.3.9`, `Java version: 1.8.0_212, vendor: Oracle Corporation`
  * Java Version: (java -version) `openjdk version "1.8.0_212"`, `OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)`
  * Platform & OS: Android 8 and 9, Samsung Galaxy S8+ device
  * Other Relevant Libraries: `geopackage-android-map:3.2.0`, `geopackage-android:3.2.0`

#### Expected Results:

  * What did you expect to happen?
Loading a large GeoPackage file (~2GB) should complete at a reasonable amount of time

#### Observed Results:

  * What happened instead?
File loads at about ~1 minute. Potentially my Android application can expect to input even larger files, and the hope is those can load reasonably fast as well (relatively speaking)

  * How often does this occur?
100%

#### Output:

  * Any logs, errors, or output messages?
No errors. The file ultimately loads, but it takes a very long time, and it is not a good user experience. Users tend to forget the the file is loading or they get impatient and cancels the download altogether.

**Comment by bosborn** [comment]
[Changed the buffer size to a modifiable static variable](https://github.com/ngageoint/geopackage-core-java/commit/0c3321d41b16e6125377d22c1555c5a8be5af5a9), defaulted at 8k bytes.  Let me know how that works.  I should be releasing new library versions in the next few weeks.

If the file exists or is moved to an externally readable (and potentially writable) location, you can [try the external link imports](https://github.com/ngageoint/geopackage-android/blob/d19e9fcc636462c0f0ae1b7eca4acafae48de21b/geopackage-sdk/src/main/java/mil/nga/geopackage/GeoPackageManager.java#L560).  The file is not copied and is read and/or modified at the external location.

**Comment by acespring78** [comment]
@bosborn Thank you! I tried the external link imports you suggested and that actually works a lot better for me! I'm able to import my 2GB GeoPackage map to my Android application in a matter of seconds! Didn't know about this API so thanks for pointing this out for me!

**Comment by bosborn** [comment]
Released the buffer size change in [3.3.0](https://github.com/ngageoint/geopackage-core-java/blob/3.3.0/src/main/java/mil/nga/geopackage/io/GeoPackageIOUtils.java).
